name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build & Run Tests
    runs-on: ubuntu-latest
    container:
      image: php:8.1-cli-buster
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Container
      run: |
          apt update && \
            apt install --no-install-recommends --assume-yes --quiet git \
            software-properties-common \
            tar \
            vim \
            zip \
            unzip \
            apt-transport-https \
            ca-certificates \
            curl \
            zlib1g-dev \
            libzip-dev

          docker-php-ext-install zip

          curl -sS https://getcomposer.org/installer | php 
          mv composer.phar /usr/local/bin/composer
          chmod +x /usr/local/bin/composer
          
          cd /var/www/html
          
    - name: Install Composer
      run: |
          composer install
    - name: Run Tests
      run: |
          vendor/bin/phpunit
