name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up Container and run tests
      run: |
          FROM php:8.1-cli-buster
          RUN apt update && \
              apt install --no-install-recommends --assume-yes --quiet git \
            software-properties-common \
            tar \
            vim \
            zip \
            unzip \
            apt-transport-https \
            ca-certificates \
            curl \
            zlib1g-dev \
            libzip-dev

          RUN docker-php-ext-install zip
          RUN pecl channel-update pecl.php.net

          COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
          WORKDIR /var/www/html

          COPY . /var/www/html

          CMD composer install && vendor/bin/phpunit
